drop table male;
create table male(
    name varchar2(30)
    ,user_id varchar2(30)
    ,user_pw varchar2(50)
    ,grade number(1)
    ,age number(3)
    ,height number(3)
    ,bmi number(5, 3)
    ,latest_edu_level number(1)
    ,latest_edu_string  varchar2(20)
    ,salary number(20)
    ,total_score number(5,2)
    ,normalized_total_score number(4)
    ,cash number(20)
    ,edu_score number(2)
    ,salary_score number(3)
    ,height_score number(2)
    ,match_receiver varchar2(1)
    ,matched_id varchar2(30)
    ,match_lock number(1)
    ,match_finish number(1)
    ,account_lock number(1)
    ,lock_count number(1)
    ,taco   number(1)
    );